# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 06:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('last_date', models.DateField(blank=True)),
                ('salary', models.PositiveIntegerField(blank=True)),
                ('Job_responsibility', models.TextField()),
                ('candidate_profile', models.TextField()),
                ('posted_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appliers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_apply', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jportal.AddJob')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Depend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jportal.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('specialization', models.CharField(blank=True, max_length=50)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('year', models.CharField(blank=True, max_length=10)),
                ('grading_system', models.CharField(blank=True, max_length=50)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
                ('school', models.CharField(blank=True, max_length=200)),
                ('board', models.CharField(blank=True, max_length=10)),
                ('medium', models.CharField(blank=True, max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Education',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, upload_to='employer_pic')),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True)),
                ('contact_no', models.CharField(max_length=10)),
                ('email_verify', models.BooleanField(default=False)),
                ('approval', models.BooleanField(default=False)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='jportal.City')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerCompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField()),
                ('logo', models.ImageField(blank=True, upload_to='company_logo')),
                ('employer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jportal.Employer')),
            ],
        ),
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Graduation',
            },
        ),
        migrations.CreateModel(
            name='JobSeekers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(blank=True, upload_to='')),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField(blank=True)),
                ('contact_no', models.CharField(max_length=10)),
                ('email_verify', models.BooleanField(default=False)),
                ('phone_verify', models.BooleanField(default=False)),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='jportal.City')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeekersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_profile', models.CharField(blank=True, max_length=200)),
                ('pref_job_loc', models.CharField(blank=True, max_length=100)),
                ('resume', models.FileField(blank=True, upload_to='resume')),
                ('key_skills', models.TextField()),
                ('total_workexp', models.CharField(max_length=20)),
                ('current_drawn_sal', models.PositiveIntegerField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Category')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Education')),
                ('jobseeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jportal.JobSeekers')),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.EmailField(max_length=254)),
                ('sent_date', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=500)),
                ('sent_to', models.CharField(blank=True, max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='PhD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'PhD',
            },
        ),
        migrations.CreateModel(
            name='Post_Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Post Graduation',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Category')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='jportal.City')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jportal.Category')),
            ],
            options={
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='Subscribtion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_status', models.BooleanField(default=False)),
                ('subscriber_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='search',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.State'),
        ),
        migrations.AddField(
            model_name='search',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='jportal.SubCategory'),
        ),
        migrations.AddField(
            model_name='jobseekersprofile',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='jportal.SubCategory'),
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.State'),
        ),
        migrations.AddField(
            model_name='jobseekers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employer',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.State'),
        ),
        migrations.AddField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='education',
            name='graduation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Graduation'),
        ),
        migrations.AddField(
            model_name='education',
            name='jobseeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jportal.JobSeekers'),
        ),
        migrations.AddField(
            model_name='education',
            name='phd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.PhD'),
        ),
        migrations.AddField(
            model_name='education',
            name='post_graduation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Post_Graduation'),
        ),
        migrations.AddField(
            model_name='depend',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='jportal.SubCategory'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jportal.State'),
        ),
        migrations.AddField(
            model_name='appliers',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jportal.JobSeekers'),
        ),
        migrations.AddField(
            model_name='addjob',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jportal.Category'),
        ),
        migrations.AddField(
            model_name='addjob',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jportal.Employer'),
        ),
        migrations.AddField(
            model_name='addjob',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='jportal.SubCategory'),
        ),
    ]
