# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-30 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='last_date',
            field=models.DateField(blank=True),
        ),
    ]
