# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jportal.Category')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='jportal.SubCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='employer',
        ),
        migrations.AlterField(
            model_name='appliers',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jportal.AddJob'),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
