# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
