# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='designation',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
