# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekersprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobseekersprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobseekersprofile',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='jobseekersprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobSeekersProfile',
        ),
    ]
