# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-12 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2),
        ),
    ]
