# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekersprofile',
            name='total_workexp',
            field=models.CharField(max_length=20),
        ),
    ]
