# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0002_employer_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='designation',
            field=models.CharField(max_length=30),
        ),
    ]
