# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0002_auto_20180215_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='jobseeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jportal.JobSeekers'),
        ),
    ]
