# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='jobseeker',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='jportal.JobSeekers'),
            preserve_default=False,
        ),
    ]
