# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0002_auto_20180118_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_category',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='appliers',
            name='applier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jportal.JobSeekers'),
        ),
    ]
