# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0002_auto_20180208_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekersProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_job_loc', models.CharField(blank=True, max_length=100)),
                ('resume', models.FileField(blank=True, upload_to='')),
                ('key_skills', models.TextField()),
                ('total_workexp', models.DateTimeField()),
                ('current_drawn_sal', models.PositiveIntegerField(blank=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Category')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Education')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='jportal.SubCategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jportal.JobSeekers')),
            ],
        ),
    ]
