# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0002_auto_20180208_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depend',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jportal.Category'),
        ),
        migrations.AlterField(
            model_name='depend',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='jportal.SubCategory'),
        ),
    ]
