# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0002_auto_20180130_1202'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployerProfile',
            new_name='EmployerCompanyProfile',
        ),
    ]
