# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-03 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0002_auto_20180301_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depend',
            name='category',
        ),
        migrations.RemoveField(
            model_name='depend',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='addjob',
            name='salary',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='Depend',
        ),
    ]
