# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0003_auto_20180119_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
