# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0003_education_jobseeker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekersprofile',
            name='education',
        ),
        migrations.AddField(
            model_name='jobseekersprofile',
            name='education',
            field=models.ManyToManyField(null=True, to='jportal.Education'),
        ),
    ]
