# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 07:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0003_auto_20180212_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekersprofile',
            old_name='user',
            new_name='jobseeker',
        ),
        migrations.AddField(
            model_name='education',
            name='jobseeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jportal.JobSeekers'),
        ),
    ]
