# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0003_jobseekersprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='education',
        ),
        migrations.AddField(
            model_name='education',
            name='board',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='education',
            name='grading_system',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='graduation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='marks',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='education',
            name='medium',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='education',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='education',
            name='school',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='specialization',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='education',
            name='university',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='education',
            name='year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
