# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0003_auto_20180212_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
