# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 10:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0004_auto_20180215_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekersprofile',
            name='education',
        ),
        migrations.AddField(
            model_name='jobseekersprofile',
            name='education',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Education'),
        ),
    ]
