# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0004_auto_20180213_0717'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Category')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='jportal.SubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='SearchLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='name',
            new_name='state',
        ),
        migrations.AddField(
            model_name='searchlocation',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='jportal.City'),
        ),
        migrations.AddField(
            model_name='searchlocation',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.State'),
        ),
    ]
