# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-03 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0004_auto_20180303_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='salary',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
