# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0004_auto_20180119_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='website',
        ),
        migrations.AddField(
            model_name='employercompanyprofile',
            name='employer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jportal.Employer'),
        ),
    ]
