# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0004_auto_20180208_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Graduation',
            },
        ),
        migrations.CreateModel(
            name='PhD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'PhD',
            },
        ),
        migrations.CreateModel(
            name='Post_Graduation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Post Graduation',
            },
        ),
        migrations.AlterModelOptions(
            name='jobseekers',
            options={'verbose_name_plural': 'JobSeekers'},
        ),
        migrations.AlterField(
            model_name='education',
            name='graduation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Graduation'),
        ),
        migrations.AddField(
            model_name='education',
            name='phd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.PhD'),
        ),
        migrations.AddField(
            model_name='education',
            name='post_graduation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Post_Graduation'),
        ),
    ]
