# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0005_auto_20180303_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekers',
            name='designation',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
