# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0005_auto_20180215_1058'),
        ('jportal', '0003_auto_20180215_0848'),
    ]

    operations = [
    ]
