# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0005_auto_20180119_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='con_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
