# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0006_auto_20180119_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
