# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-12 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0006_jobseekers_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekers',
            name='designation',
        ),
    ]
