# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0006_auto_20180217_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Category')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='jportal.City')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.State')),
                ('subcategory', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='jportal.SubCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='searchcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='searchcategory',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='searchlocation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='searchlocation',
            name='state',
        ),
        migrations.AlterField(
            model_name='employer',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='jportal.City'),
        ),
        migrations.DeleteModel(
            name='SearchCategory',
        ),
        migrations.DeleteModel(
            name='SearchLocation',
        ),
    ]
