# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 11:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0007_auto_20180215_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='depend',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.City'),
        ),
        migrations.AddField(
            model_name='depend',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.State'),
        ),
    ]
