# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-17 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0007_auto_20180217_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekersprofile',
            name='total_workexp',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='search',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', on_delete=django.db.models.deletion.CASCADE, to='jportal.City'),
        ),
        migrations.AlterField(
            model_name='search',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.State'),
        ),
        migrations.AlterField(
            model_name='search',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='category', chained_model_field='category', on_delete=django.db.models.deletion.CASCADE, to='jportal.SubCategory'),
        ),
    ]
