# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-24 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0008_auto_20180217_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekersprofile',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='search',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Category'),
        ),
    ]
