# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0008_auto_20180215_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depend',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.City'),
        ),
        migrations.AlterField(
            model_name='depend',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.State'),
        ),
    ]
