# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0008_auto_20180119_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='con_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='jobseekers',
            name='con_no',
            field=models.PositiveIntegerField(),
        ),
    ]
