# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-14 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0008_auto_20180312_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekers',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='jobseeker_pic'),
        ),
    ]
