# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0009_auto_20180122_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='dob',
            field=models.DateField(blank=True),
        ),
    ]
