# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0009_auto_20180224_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekers',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='jobseeker_pic'),
        ),
    ]
