# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-24 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0009_auto_20180216_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekersprofile',
            old_name='user',
            new_name='jobseeker',
        ),
        migrations.AddField(
            model_name='jobseekersprofile',
            name='linkedin_profile',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
