# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0010_auto_20180122_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='con_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='employer',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='employer_pic'),
        ),
        migrations.AlterField(
            model_name='jobseekers',
            name='con_no',
            field=models.CharField(max_length=10),
        ),
    ]
