# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0010_auto_20180314_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.City'),
        ),
        migrations.AddField(
            model_name='addjob',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.State'),
        ),
    ]
