# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-26 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0010_auto_20180226_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addjob',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appliers',
            name='date_apply',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobseekersprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to='resume'),
        ),
    ]
