# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0011_savejobseeker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savejobseeker',
            name='emp',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jportal.Employer'),
        ),
    ]
