# Generated by Django 2.0.2 on 2018-02-26 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0011_auto_20180226_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depend',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Category'),
        ),
        migrations.AlterField(
            model_name='depend',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.State'),
        ),
    ]
