# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 06:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0013_auto_20180315_0615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savejobseeker',
            name='emp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jportal.Employer'),
        ),
        migrations.AlterField(
            model_name='savejobseeker',
            name='jobseeker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jportal.JobSeekers'),
        ),
    ]
