# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0016_auto_20180315_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jportal.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Banners_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=200)),
                ('state', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='jportal.State')),
            ],
        ),
    ]
