# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0017_banners_category_banners_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners_category',
            name='img',
            field=models.ImageField(upload_to='banners/category/'),
        ),
        migrations.AlterField(
            model_name='banners_state',
            name='img',
            field=models.ImageField(upload_to='banners/state/'),
        ),
    ]
