# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0018_auto_20180319_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners_state',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', default=1, on_delete=django.db.models.deletion.CASCADE, to='jportal.City'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='banners_state',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
