# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 13:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0021_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='addjob',
            name='city',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='state', chained_model_field='state', null=True, on_delete=django.db.models.deletion.CASCADE, to='jportal.City'),
        ),
        migrations.AddField(
            model_name='addjob',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jportal.State'),
        ),
    ]
