# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0022_auto_20180323_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='year',
            new_name='end_year',
        ),
        migrations.AddField(
            model_name='education',
            name='start_year',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
