# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0024_auto_20180403_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='stream',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
