# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0025_education_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekersprofile',
            name='total_workexp',
            field=models.TextField(default='', null=True),
        ),
    ]
