# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0026_auto_20180426_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekersprofile',
            old_name='total_workexp',
            new_name='experience',
        ),
    ]
