# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0027_auto_20180426_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekersprofile',
            name='hobbies',
            field=models.TextField(default='', null=True),
        ),
    ]
