# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0028_jobseekersprofile_hobbies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekersprofile',
            old_name='current_drawn_sal',
            new_name='current_drawn_salary',
        ),
    ]
