# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 11:44
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0029_auto_20180426_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekersprofile',
            name='subcategory',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='category', chained_model_field='category', null=True, on_delete=django.db.models.deletion.CASCADE, to='jportal.SubCategory'),
        ),
    ]
