# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-26 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jportal', '0030_auto_20180426_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='profile_img',
            field=models.ImageField(blank=True, default='user.png', upload_to='employer_pic'),
        ),
        migrations.AlterField(
            model_name='jobseekers',
            name='profile_img',
            field=models.ImageField(blank=True, default='user.png', upload_to='jobseeker_pic'),
        ),
    ]
